apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gop-file-server
  name: gop-file-server
spec:
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
  containers:
  - image: kodekloud/fileserver
    imagePullPolicy: IfNotPresent
    name: gop-file-server
    volumeMounts:
       - name: data-store
         mountPath: /web
  dnsPolicy: ClusterFirst
  restartPolicy: Never

---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: data-pv
spec:
   accessModes: ["ReadWriteMany"]
   capacity:
    storage: 1Gi
   hostPath:
      path: /web
      type: DirectoryOrCreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: data-pvc
spec:
   accessModes: ["ReadWriteMany"]
   resources:
    requests:
       storage: 1Gi
   volumeName: data-pv


