apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sega
  name: sega
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: tails

  - image: nginx
    name: sonic
    env:
    - name: NGINX_PORT
      value: "8080"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
~              
