apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "ckad-mock-exam-solution.com"
    http:
      paths:
      - pathType: Prefix
        path: "/video"
        backend:
          service:
            name: my-video-service
            port:
              number: 8080

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx1401
  name: nginx1401
spec:
  containers:
  - image: nginx
    name: nginx1401
    resources: {}
    livenessProbe:
      exec:
        command:
        - ls
        - /var/www/html/probe
      initialDelaySeconds: 10
      periodSeconds: 60
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay
spec:
  completions: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      restartPolicy: Never
      containers:
      - name: whalesay
        image: docker/whalesay
        command:
        - sh
        - -c
        - "cowsay I am going to ace CKAD!"
  backoffLimit: 6
~                       
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - args:
    - sleep
    - "4800"
    image: busybox
    name: europa
    resources: {}
    env:
    - name: type 
      value: moon
  - image: nginx
    name: jupiter
    resources: {}
    env:
    - name: type 
      value: planet
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-volume
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/data
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain








